backend:
  name: git-gateway
  repo: cultuur-gif/expertisedag-gatsby
  branch: content

media_folder: src/images

publish_mode: editorial_workflow

display_url: https://content.genm18.com

editor:
   preview: false

collections:
  - name: blog
    label: Blogpost
    folder: src/content/blogposts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: authors, label: Authors, widget: list }
      - { name: body, label: Text, widget: markdown }
  - name: event
    label: Event
    folder: src/content/home/agenda
    create: true
    fields:
      - { name: startTime, label: Starting Time, widget: datetime, required: true }
      - { name: endTime, label: Ending Time, widget: datetime, required: true }
      - { name: title, label: Title, required: true, default: Event }
      - { name: room, label: Location }
      - { name: order, label: Order, widget: number }
      - { name: url, label: Attachment or URL }
      - { name: body, label: Text, widget: markdown }
  - name: person
    label: Person
    folder: src/content/home/persons
    create: true
    fields:
      - { name: name, label: Name, default: John Doe }
      - { name: function, label: Function}
      - { name: smallImage, label: Image, widget: custompathimage, customMediaPath: "../../../images/", rawMediaPath: "https://raw.githubusercontent.com/cultuur-gif/expertisedag-gatsby/content/src/images/"}
      - { name: largeImage, label: Image, widget: custompathimage, customMediaPath: "../../../images/", rawMediaPath: "https://raw.githubusercontent.com/cultuur-gif/expertisedag-gatsby/content/src/images/"}
      - { name: blur, label: Blurred?, widget: boolean}
      - { name: personType, label: Person Type, widget: select, default: speaker, options: [speaker, casestudy, debate], required: true }
      - { name: body, label: Text, widget: markdown}
